mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from django.contrib.auth import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/login/$', views.login, name='login'),
    url(r'', include('website.urls')),
]

website/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    url(r'^$', views.post, name='post_list'),
    url(r'^admin_page$', views.admin_page, name='admin_page'),
    url(r'^admin_page/(?P<pk>\d+)/$', views.admin_page, name='admin_page'),
    url(r'^post/new/$', views.displayPost_new, name='displayPost_new'),
    url(r'^post/(?P<pk>\d+)/$', views.work_detail, name='work_detail'),
    url(r'^post/(?P<pk>\d+)/edit/$', views.display_edit, name='display_edit'),
]
if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone




# Create your models here.

class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.DO_NOTHING)
    title = models.CharField('Title', max_length=200)
    text = models.TextField('Description')
    image = models.ImageField(upload_to='img', height_field=None, width_field=None)
    number = models.IntegerField(default = 0)
    url1 = models.URLField(default='URL')
    url1text = models.CharField(default='URL', max_length=200)
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank = True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

class Admin(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.DO_NOTHING)
    title = models.CharField('Title', max_length=200)
    text = models.TextField('Description')
    resume = models.FileField(upload_to=' ')
    location = models.CharField(default='Berlin', max_length=200)
    phone = models.CharField(default='Your number', max_length=200)
    email = models.EmailField(default='Your mail')
    url1 = models.URLField(default='URL')
    url1text = models.CharField(default='URL', max_length=200)
    url2 = models.URLField(default='URL')
    url2text = models.CharField(default='URL', max_length=200)
    url3 = models.URLField(default='URL')
    url3text = models.CharField(default='URL', max_length=200)
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank = True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

website/forms.py
from django import forms
from django.core.files.uploadedfile import SimpleUploadedFile
from .models import Post, Admin
from .helperfunctions import randomnumber

class DisplayPost(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text', 'image', 'url1', 'number')
        image = forms.ImageField(
            label='select an image file'
        )

class Admin(forms.ModelForm):

    class Meta:
        model = Admin
        fields = ('title', 'text', 'url1', 'url2', 'url3', 'email', 'phone', 'location'
        )
        resume = forms.FileField(
            label='select a file'
        )



class ContactForm(forms.Form):
    name = forms.CharField(max_length=100)
    subject = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)
    sender = forms.EmailField()
    cc_myself = forms.BooleanField(required=False)

f = DisplayPost()
f.as_p()
print (randomnumber())
print (f.as_p())

website/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.core.files.uploadedfile import SimpleUploadedFile
from django.core.mail import send_mail
from django.shortcuts import render, get_object_or_404
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from .models import Post as Post_model
from .models import Admin as Admin_model
from .forms import DisplayPost, ContactForm, Admin
from .helperfunctions import randomnumber


# Create your views here.

def post(request):
    admin = Admin_model.objects.get(title='Admin')
    works = Post_model.objects.filter(title__contains=' ')#.order_by('published_date')
    return render(request, 'website/post_list.html', {'admin': admin, 'works': works})
    # return render(request, 'website/post_list.html', {'works': works})

@login_required
def admin_page(request, pk):

    post = get_object_or_404(Post_model.objects, pk=pk)
    if request.method == "POST":
        form = Admin_model(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('post_list')
    else:
        form = Admin_model(instance=post)
    print (form.as_p())
    return render(request, 'website/admin_page.html', {'form': form})


def work_detail(request, pk):

    work = get_object_or_404(Post_model, pk=pk)
    return render(request, 'website/work_detail.html', {'work': work})

@login_required
def displayPost_new(request):

    if request.method == "POST":
        form = DisplayPost(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit= False)
            post.author = request.user
            post.published_date = timezone.now()
            post.number = randomnumber()
            post = Post(image = request.FILES['image'])
            post.save()
            return redirect('post_list')
    else:
        form = DisplayPost()
    print (form.as_p())
    return render(request, 'website/display_edit.html', {'form': form})

@login_required
def display_edit(request, pk):

    post = get_object_or_404(Post_model, pk=pk)
    if request.method == "POST":
        form = DisplayPost(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post = Post_model(image = request.FILES['image'])
            post.save()
            return redirect('work_detail', pk=post.pk)
    else:
        form = DisplayPost(instance=post)
    print (form.as_p())
    return render(request, 'website/display_edit.html', {'form': form})


def sendMail(request):

    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']
            sender = form.cleaned_data['sender']
            cc_myself = form.cleaned_data['cc_myself']

            recipients =['tanja@transfeld.net']
            if cc_myself:
                recipients.append(sender)

            send_mail(subject, message, sender, recipients, name)
            return redirect('post_list')
    else:
        form = ContactForm()
        return render(request, 'website/post_list.html', {'form': form})
            #return HttpResponseRedirect('/thanks/')
            #idee: alternative post_list seite mit inaktivem formular,mit danke

#def work(request):
    #work_content = Work.objects.all()
    # work_content = Work.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    #return render(request, 'website/work.html', {'work_content': work_content})

#def contact(request):
    #contact_content = Contact.objects.all()
    #return render(request, 'website/post_list.html', {'contact_content': contact_content})

website/templates/website/admin.html
{% extends 'website/base.html' %}
{% block admin %}



<!--
    <h3 class="w3-padding-16 w3-text-light-grey">My Skills</h3>
    <p class="w3-wide">Photography</p>
    <div class="w3-white">
      <div class="w3-dark-grey" style="height:28px;width:95%"></div>
    </div>
    <p class="w3-wide">Web Design</p>
    <div class="w3-white">
      <div class="w3-dark-grey" style="height:28px;width:85%"></div>
    </div>
    <p class="w3-wide">Photoshop</p>
    <div class="w3-white">
      <div class="w3-dark-grey" style="height:28px;width:80%"></div>
    </div><br>
    <div class="w3-row w3-center w3-padding-16 w3-section w3-light-grey">
      <div class="w3-quarter w3-section">
        <span class="w3-xlarge">11+</span><br>
        Partners
      </div>
      <div class="w3-quarter w3-section">
        <span class="w3-xlarge">55+</span><br>
        Projects Done
      </div>
      <div class="w3-quarter w3-section">
        <span class="w3-xlarge">89+</span><br>
        Happy Clients
      </div>
      <div class="w3-quarter w3-section">
        <span class="w3-xlarge">150+</span><br>
        Meetings
      </div>
    </div>

    <button class="w3-button w3-light-grey w3-padding-large w3-section">
      <i class="fa fa-download"></i> Download Resume
    </button>
-->
    <!-- Grid for pricing tables -->
<!--
    <h3 class="w3-padding-16 w3-text-light-grey">My Price</h3>
    <div class="w3-row-padding" style="margin:0 -16px">
      <div class="w3-half w3-margin-bottom">
        <ul class="w3-ul w3-white w3-center w3-opacity w3-hover-opacity-off">
          <li class="w3-dark-grey w3-xlarge w3-padding-32">Basic</li>
          <li class="w3-padding-16">Web Design</li>
          <li class="w3-padding-16">Photography</li>
          <li class="w3-padding-16">5GB Storage</li>
          <li class="w3-padding-16">Mail Support</li>
          <li class="w3-padding-16">
            <h2>$ 10</h2>
            <span class="w3-opacity">per month</span>
          </li>
          <li class="w3-light-grey w3-padding-24">
            <button class="w3-button w3-white w3-padding-large w3-hover-black">Sign Up</button>
          </li>
        </ul>
      </div>

      <div class="w3-half">
        <ul class="w3-ul w3-white w3-center w3-opacity w3-hover-opacity-off">
          <li class="w3-dark-grey w3-xlarge w3-padding-32">Pro</li>
          <li class="w3-padding-16">Web Design</li>
          <li class="w3-padding-16">Photography</li>
          <li class="w3-padding-16">50GB Storage</li>
          <li class="w3-padding-16">Endless Support</li>
          <li class="w3-padding-16">
            <h2>$ 25</h2>
            <span class="w3-opacity">per month</span>
          </li>
          <li class="w3-light-grey w3-padding-24">
            <button class="w3-button w3-white w3-padding-large w3-hover-black">Sign Up</button>
          </li>
        </ul>
      </div>
-->
    <!-- End Grid/Pricing tables -->
<!--
    </div>
-->
    <!-- Testimonials -->
<!--
    <h3 class="w3-padding-24 w3-text-light-grey">My Reputation</h3>
    <img src="/w3images/bandmember.jpg" alt="Avatar" class="w3-left w3-circle w3-margin-right" style="width:80px">
    <p><span class="w3-large w3-margin-right">Chris Fox.</span> CEO at Mighty Schools.</p>
    <p>Jane Doe saved us from a web disaster.</p><br>

    <img src="/w3images/avatar_g2.jpg" alt="Avatar" class="w3-left w3-circle w3-margin-right" style="width:80px">
    <p><span class="w3-large w3-margin-right">Rebecca Flex.</span> CEO at Company.</p>
    <p>No one is better than Jane Doe.</p>
-->
  <!-- End About Section -->
  </div>



{% endblock %}
    <!-- Footer -->

website/templates/website/admin_page.html
{% extends 'website/base.html' %}
{% block content %}


<!-- Page Content -->
<div class="w3-padding-large" id="main">


  <!-- About Section -->
  <div class="w3-content w3-justify w3-text-grey w3-padding-64" id="about">
    <h2 class="w3-text-light-grey">Change About Section</h2>
    <hr style="width:200px" class="w3-opacity">
    <p>


      <form method="POST">{% csrf_token %}
        {{ form.nonfield_errors }}
        <div class="fieldWrapper">
          {{ form.title.errors }}
          <label for="{{ form.title.id_for_label }}"></label> <input class = "w3-input w3-padding-16" value="{{ form.title.value }}" type="text" name="title" placeholder="Titel" required id="id_title" maxlength="200" required/>
        </div>

        <p>
          <div class="fieldWrapper">
            {{ form.text.errors }}
            <label for="{{ form.text.id_for_label }}"></label>
              <textarea class = "w3-input w3-padding-16" type="text" name="text" placeholder="Text" required id="id_text" rows="10" cols="40" required />
              {{ form.text.value }}
              </textarea>
          </div>
        <p>



          <button class="button-normal w3-text-light-grey" type="submit">
            <i class="fa fa-paper-plane"></i> Save
          </button>

      </form>
    </div>
    </p>

{% endblock %}
    <!-- Footer -->

website/templates/website/admin_page_detail.html
{% extends 'website/base.html' %}
{% block content %}


<!-- Icon Bar (Sidebar - hidden on small screens) -->
<nav class="w3-sidebar w3-bar-block w3-small w3-hide-small w3-center">
  <!-- Avatar image in top left corner
  <img src="/w3images/avatar_smoke.jpg" style="width:100%"> -->
  <h1>☠️</h1>
  <a href="/#" class="w3-bar-item w3-button w3-padding-large w3-black">
    <i class="fa fa-home w3-xxlarge"></i>
    <p>HOME</p>
  </a>

  <a href="/#about" class="w3-bar-item w3-button w3-padding-large w3-hover-black">
    <i class="fa fa-user w3-xxlarge"></i>
    <p>ABOUT</p>
  </a>
  <a href="/#photos" class="w3-bar-item w3-button w3-padding-large w3-hover-black">
    <i class="fa fa-eye w3-xxlarge"></i>
    <p>WORK</p>
  </a>
  <a href="/#contact" class="w3-bar-item w3-button w3-padding-large w3-hover-black">
    <i class="fa fa-at w3-xxlarge"></i>
    <p>CONTACT</p>
  </a>
  {% if user.is_authenticated %}
  <a href="{% url 'admin_page' %}" class="w3-bar-item w3-button w3-padding-large w3-hover-black">
    <i class="fa fa-plus w3-xxlarge"></i>
    <p>+</p>
  </a>
  {% endif %}
</nav>

<!-- Navbar on small screens (Hidden on medium and large screens) -->
<div class="w3-top w3-hide-large w3-hide-medium" id="myNavbar">
  <div class="w3-bar w3-black w3-opacity w3-hover-opacity-off w3-center w3-small">
    <a href="#" class="w3-bar-item w3-button" style="width:25% !important">HOME</a>
    <a href="#about" class="w3-bar-item w3-button" style="width:25% !important">ABOUT</a>
    <a href="#photos" class="w3-bar-item w3-button" style="width:25% !important">HOME</a>
    <a href="#contact" class="w3-bar-item w3-button" style="width:25% !important">CONTACT</a>
  </div>
</div>

<!-- Page Content -->
<div class="w3-padding-large" id="main">


  <!-- About Section -->
  <div class="w3-content w3-justify w3-text-grey w3-padding-64" id="about">
    {% if user.is_authenticated %}
    <h2 class="w3-text-light-grey">About
      <a href=" " class="w3-text-light-grey">
        <button class="button">
        <i class="fa fa-gears w3-text-light-grey"></i>
        </button></a>
    </h2>
    {% else %}
    <h2 class="w3-text-light-grey">About</h2>
    {% endif %}
    <hr style="width:200px" class="w3-opacity">
    <p>{{ about.text }}
    </p>
      <a href="/media/resume.pdf" class="w3-text-light-grey">
      <button class="button">
        <i class="fa fa-download"></i> Download Resume
      </button></a>

{% endblock %}
    <!-- Footer -->

website/templates/website/display_edit.html
{% extends 'website/base.html' %}
{% block content %}
<div class="w3-padding-large" id="main">

<h1>New piece of work</h1>
    <form enctype="multipart/form-data" method="POST" action: "/inc/" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>

    <form enctype="multipart/form-data" method="POST" action: "/inc/">{% csrf_token %}
      {{ form.nonfield_errors }}
      <div class="fieldWrapper">
        {{ form.title.errors }}
        <label for="{{ form.title.id_for_label }}"></label>
        <input class = "w3-input w3-padding-16" value="{{ form.title.value }}" type="text" name="title" placeholder=" " required id="id_title" maxlength="200" required/>
      </div>
      <p>
      <div class="fieldWrapper">
        {{ form.text.errors }}
        <label for="{{ form.text.id_for_label }}"></label>
          <textarea class = "w3-input w3-padding-16" type="text" name="text" placeholder="Text" required id="id_text" rows="10" cols="40" required />
          {{ form.text.value }}
          </textarea>
      </div>
      <p>
      <div class="fieldWrapper">
        {{ form.image.errors }}

        <label for="file"></label>Currently: <a href="{{ form.image.url }}">{{ form.image.value }}</a><br />

        <input class = "inputfile button-normal" type="file" name="image" id="file"/>
        <label for="file"><i class="fa fa-paper-plane"></i>Change:</label>input#id_image
      </div>



        <button class="button-normal w3-text-light-grey" type="submit">
          <i class="fa fa-paper-plane"></i> Save
        </button>

    </form>


{% endblock %}

website/templates/website/display_edit_full.html
{% extends 'website/base.html' %}
{% block content %}


<!-- Page Content -->
<div class="w3-padding-large" id="main">


  <!-- About Section -->
  <div class="w3-content w3-justify w3-text-grey w3-padding-64" id="about">
    <h2 class="w3-text-light-grey">New piece of work</h2>
    <hr style="width:200px" class="w3-opacity">
    <p>


      <form enctype="multipart/form-data" method="POST" action: "/inc/">{% csrf_token %}
        {{ form.nonfield_errors }}
        <div class="fieldWrapper">
          {{ form.title.errors }}
          <label for="{{ form.title.id_for_label }}"></label>
          <input class = "w3-input w3-padding-16" value="{{ form.title.value }}" type="text" name="title" placeholder=" " required id="id_title" maxlength="200" required/>
        </div>
        <p>
        <div class="fieldWrapper">
          {{ form.text.errors }}
          <label for="{{ form.text.id_for_label }}"></label>
            <textarea class = "w3-input w3-padding-16" type="text" name="text" placeholder="Text" required id="id_text" rows="10" cols="40" required />
            {{ form.text.value }}
            </textarea>
        </div>
        <p>
        <div class="fieldWrapper">
          {{ form.image.errors }}
          <label for="file"></label>Currently: <a href="{{ form.image.url }}">{{ form.image.value }}</a><br />
          Change:
          <input class = "w3-button w3-hover-black" type="file" name="image" id="file"/>
        </div>


          <button class="button-normal w3-text-light-grey" type="submit">
            <i class="fa fa-paper-plane"></i> Save
          </button>

      </form>
    </div>
    </p>

{% endblock %}
    <!-- Footer -->

website/templates/website/navbar.html
{% extends 'website/base.html' %}
{% block navbar %}



{% endblock %}

website/templates/website/post_list.html
{% extends 'website/base.html' %}
{% block content %}




<!-- Page Content -->
<div class="w3-padding-large" id="main">
  <!-- Header/Home -->
  <header class="w3-container w3-padding-32 w3-center w3-black" id="home">
    <h1 class="w3-jumbo"><span class="w3-hide-small">I'm</span> Mirabellensaft.</h1>
    <p>Chemist, Artist and Coder.</p>
    <img src="/media/img/0005.jpg" alt="boy" class="w3-image" width="200" >
  </header>

  <!-- About Section -->
  <div class="w3-content w3-justify w3-padding-64" id="about">
    {% if user.is_authenticated %}
    <h2 class="w3-text-light-grey">About
      <a href="{% url 'admin_page' pk=admin.pk %}" class="w3-text-light-grey">
        <button class="button-tiny">
        <i class="fa fa-gears w3-text-light-grey"></i>
        </button></a>
    </h2>
    {% else %}
    <h2 class="w3-text-light-grey">About</h2>
    {% endif %}
    <hr style="width:200px" class="w3-opacity">
    <p>{{ admin.text }}
    </p>
      <a href="/media/resume.pdf" class="w3-text-light-grey">
      <button class="button-normal w3-text-light-grey">
        <i class="fa fa-download"></i> Download Resume
      </button></a>

  <!-- Portfolio Section -->
  <div class="w3-padding-64 w3-content" id="photos">
    {% if user.is_authenticated %}
    <h2 class="w3-text-light-grey">My Work
      <a href="{% url 'displayPost_new' %}" class="w3-text-light-grey">
        <button class="button-tiny">
        <i class="fa fa-plus w3-text-light-grey"></i>
        </button></a>
    </h2>
    {% else %}
    <h2 class="w3-text-light-grey">My Work</h2>
    {% endif %}

    <hr style="width:200px" class="w3-opacity">

    <!-- Grid for photos -->
    <div class="w3-row-padding" style="margin:0 -16px">

      <div class="w3-third">
          {% for work in works %}
          {% if work.number == 0 %}
          <a href="{% url 'work_detail' pk=work.pk %}">
        <img src="{{ work.image.url }}" style="width:100%"></a>
          {% endif %}
          {% endfor %}
      </div>
      <div class="w3-third">
          {% for work in works %}
          {% if work.number == 1 %}
          <a href="{% url 'work_detail' pk=work.pk %}">
        <img src="{{ work.image.url }}" style="width:100%"></a>
          {% endif %}
          {% endfor %}
      </div>
      <div class="w3-third">
          {% for work in works %}
          {% if work.number == 2 %}
          <a href="{% url 'work_detail' pk=work.pk %}">
        <img src="{{ work.image.url }}" style="width:100%"></a>
          {% endif %}
          {% endfor %}
      </div>


    <!-- End photo grid -->


  <!-- End Portfolio Section -->

  </div>
  <!-- Contact Section -->
  <div class="w3-padding-64 w3-content" id="contact">
    {% if user.is_authenticated %}
    <h2 class="w3-text-light-grey">Contact Me
      <a href="/media/resume.pdf" class="w3-text-light-grey">
        <button class="button-tiny">
        <i class="fa fa-gears w3-text-light-grey"></i>
        </button></a>
    </h2>
    {% else %}
    <h2 class="w3-text-light-grey">Contact Me</h2>
    {% endif %}
    <hr style="width:200px" class="w3-opacity">

    <div class="w3-section">
      <p><i class="fa fa-map-marker fa-fw w3-text-white w3-xxlarge w3-margin-right"></i> {{ admin.location }}</p>
      <p><i class="fa fa-phone fa-fw w3-text-white w3-xxlarge w3-margin-right"></i> {{ admin.phone }}</p>
      <p><i class="fa fa-at fa-fw w3-text-white w3-xxlarge w3-margin-right"> </i> {{ admin.email }}</p>
      <p><i class="fa fa-github fa-fw w3-text-white w3-xxlarge w3-margin-right"> </i>
        <a href="{{ admin.url1 }}" class="w3-text-light-grey"> {{ admin.url1text }} </a></p>
      <p><i class="fa fa-codepen fa-fw w3-text-white w3-xxlarge w3-margin-right"> </i>
        <a href="{{ admin.url2 }}" class="w3-text-light-grey"> {{ admin.url2text }} </a></p>
      <p><i class="fa fa-twitter fa-fw w3-text-white w3-xxlarge w3-margin-right"> </i>
        <a href="{{ admin.url3 }}" class="w3-text-light-grey"> {{ admin.url3text }} </a></p>
    </div><br>
    <p>Lets get in touch. Send me a message:</p>

    <form action="/your-name/" method="post">{% csrf_token %}
      {{ form.nonfield_errors }}
      <div class="fieldWrapper">
        {{ form.name.errors }}
        <label for="{{ form.name.id_for_label }}"></label> <input class = "w3-input w3-padding-16" type="text" name="name" placeholder="Name" required id="id_name" maxlength="100" required/>
      </div>
      <p>
      <div class="fieldWrapper">
        {{ form.sender.errors }}
        <label for="{{ form.sender.id_for_label }}"></label> <input class = "w3-input w3-padding-16" type="text" name="sender" placeholder="EMail" required id="id_sender" maxlength="100" required/>
      </div></p>
      <p>
        <div class="fieldWrapper">
          {{ form.subject.errors }}
          <label for="{{ form.subject.id_for_label }}"></label> <input class = "w3-input w3-padding-16" type="text" name="subject" placeholder="Subject" required id="id_subject" maxlength="200" required/>
        </div></p>
        <p>
      <div class="fieldWrapper">
        {{ form.message.errors }}
        <label for="{{ form.message.id_for_label }}"></label> <textarea class = "w3-input w3-padding-16" type="text" name="message" placeholder="Message" required id="id_message" rows="10" cols="40" required /></textarea>
      </div></p>
      <p>
      <div class="fieldWrapper">
        {{ form.cc_myself.errors }}
        <label for="{{ form.cc_myself.id_for_label }}">Send copy to your adress?</label> <input class = "w3-check" type="checkbox" name="cc_myself" required id="id_cc_myself"/>
      </div></p>
      <p>
        <button class="button-normal  w3-text-light-grey" type="submit">
          <i class="fa fa-paper-plane"></i> Send Message
        </button>
      </p>
    </form>
  <!-- End Contact Section -->
  </div>


{% endblock %}
    <!-- Footer -->

website/templates/website/post_list1.html
{% extends 'website/base.html' %}

{% block post %}


    <div>
        <p>Contact</p>
        <p>{{ contact.location }}</p>
        <p>{{ contact.phone }}</p>
        <p>{{ contact.mail }}</p>
    </div>

    <div>
        <p>About</p>
        <p>{{ about.text }}</p>
    </div>

    <div>
        <p>Work</p>

        {% for work in works %}
        <p>{{ work.display_title }}</p>
        <p>{{ work.text }}</p>
        <p>{{ work.image }}</p>
        <p></p>
        {% endfor %}

    </div>

{% endblock %}

website/templates/website/work_detail.html
{% extends 'website/base.html' %}
{% block content %}


<!-- Page Content -->
<div class="w3-padding-large" id="main">


  <!-- About Section -->
  <div class="w3-content w3-justify w3-text-grey w3-padding-64" id="about">
    {% if user.is_authenticated %}
    <h2 class="w3-text-light-grey">{{ work.title }}
      <a href="{% url 'display_edit' pk=work.pk %}" class="w3-text-light-grey">
        <button class="button-tiny">
        <i class="fa fa-pencil w3-text-light-grey"></i>
        </button></a>
      <a href="" class="w3-text-light-grey">
        <button class="button-tiny">
        <i class="fa fa-remove w3-text-light-grey"></i>
        </button></a>
    </h2>
    {% else %}
    <h2 class="w3-text-light-grey">{{ work.title }}</h2>
    {% endif %}
    <hr style="width:200px" class="w3-opacity">

    <div class="w3-row-padding" style="margin:0 -16px">
      <div class="w3-half">
        <p><img src="/{{ work.image.url }}" style="width:100%"></a></p>
        

      </div>
      <div class="w3-half">
        <p>{{ work.text|linebreaksbr }}</p>
      </div>
    </div>


{% endblock %}
    <!-- Footer -->